universe = vanilla
Executable = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/SingleLepAnalyzer/makeTemplates/templates_M1000_2019_11_11/M_nT0p_nW0p_nB3p_nJ5/MT0pW0pB3pJ5HT.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
request_memory = 3072
Output = condor_HT.out
Error = condor_HT.err
Log = condor_HT.log
Notification = Error
Arguments = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/SingleLepAnalyzer/makeTemplates/ HT HT 1 M 0p 0p 3p 5 1000
Queue 1