use_x509userproxy = true
universe = vanilla
Executable = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/makeStep1brux.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
Transfer_Input_Files = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/makeStep1.C, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1.cc, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1.h, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1_cc.d, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1_cc.so, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/BTagCalibForLJMet.cpp, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/BTagCalibForLJMet.h, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/DeepCSV_94XSF_V4_B_F.csv
Output = TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8_44.out
Error = TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8_44.err
Log = TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8_44.log
Notification = Never
Arguments = "TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8 TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8 /store/user/lpcljm/FWLJMET102X_1lep2017_052219//TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8/singleLep2017/190528_213732/0001 /mnt/hadoop/store/user/jblee/CHiggs2017/nominal//TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8 '1275 1276 1277 1278 1279 1280 1281 1282 1283 1284 1285 1286 1287 1288 1289 1290 1291 1292 1293 1294 1295 1296 1297 1298 1299 1300 1301 1302 1303 1304' 44"

Queue 1