use_x509userproxy = true
universe = vanilla
Executable = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/makeStep1brux.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
Transfer_Input_Files = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/makeStep1.C, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1.cc, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1.h, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1_cc.d, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1_cc.so, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/BTagCalibForLJMet.cpp, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/BTagCalibForLJMet.h, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/DeepCSV_94XSF_V4_B_F.csv
Output = TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8_65.out
Error = TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8_65.err
Log = TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8_65.log
Notification = Never
Arguments = "TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8 TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8 /store/user/lpcljm/FWLJMET102X_1lep2017_052219//TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8/singleLep2017/190528_213732/0001 /mnt/hadoop/store/user/jblee/CHiggs2017/nominal//TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8 '1905 1906 1907 1908 1909 1910 1911 1912 1913 1914 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932 1933 1934' 65"

Queue 1