use_x509userproxy = true
universe = vanilla
Executable = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/makeStep1brux.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
Transfer_Input_Files = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/makeStep1.C, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1.cc, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1.h, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1_cc.d, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1_cc.so, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/BTagCalibForLJMet.cpp, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/BTagCalibForLJMet.h, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/DeepCSV_94XSF_V4_B_F.csv
Output = TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8_69.out
Error = TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8_69.err
Log = TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8_69.log
Notification = Never
Arguments = "TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8 TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8 /store/user/lpcljm/FWLJMET102X_1lep2017_052219//TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8/singleLep2017/190528_213732/0002 /mnt/hadoop/store/user/jblee/CHiggs2017/nominal//TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8 '2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027 2028 2029' 69"

Queue 1