use_x509userproxy = true
universe = vanilla
Executable = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/makeStep1brux.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
Transfer_Input_Files = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/makeStep1.C, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1.cc, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1.h, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1_cc.d, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1_cc.so, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/BTagCalibForLJMet.cpp, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/BTagCalibForLJMet.h, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/DeepCSV_94XSF_V4_B_F.csv
Output = TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8_46.out
Error = TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8_46.err
Log = TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8_46.log
Notification = Never
Arguments = "TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8 TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8 /store/user/lpcljm/FWLJMET102X_1lep2017_052219//TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8/singleLep2017/190528_213732/0001 /mnt/hadoop/store/user/jblee/CHiggs2017/nominal//TT_Mtt-1000toInf_TuneCP5_PSweights_13TeV-powheg-pythia8 '1335 1336 1337 1338 1339 1340 1341 1342 1343 1344 1345 1346 1347 1348 1349 1350 1351 1352 1353 1354 1355 1356 1357 1358 1359 1360 1361 1362 1363 1364' 46"

Queue 1