universe = vanilla
Executable = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/SingleLepAnalyzer/makeTemplates/templates_M250_2019_11_11/E_nT0p_nW0p_nB1_nJ5/ET0pW0pB1J5HT.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
request_memory = 3072
Output = condor_HT.out
Error = condor_HT.err
Log = condor_HT.log
Notification = Error
Arguments = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/SingleLepAnalyzer/makeTemplates/ HT HT 1 E 0p 0p 1 5 250
Queue 1