universe = vanilla
Executable = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/SingleLepAnalyzer/makeTemplates/templates_M250_2019_11_11/M_nT0p_nW0p_nB2_nJ6p/MT0pW0pB2J6pHT.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
request_memory = 3072
Output = condor_HT.out
Error = condor_HT.err
Log = condor_HT.log
Notification = Error
Arguments = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/SingleLepAnalyzer/makeTemplates/ HT HT 1 M 0p 0p 2 6p 250
Queue 1