use_x509userproxy = true
universe = vanilla
Executable = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/makeStep1brux.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
Transfer_Input_Files = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/makeStep1.C, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1.cc, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1.h, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1_cc.d, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1_cc.so, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/BTagCalibForLJMet.cpp, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/BTagCalibForLJMet.h, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/DeepCSV_94XSF_V4_B_F.csv
Output = TT_Mtt-700to1000_TuneCP5_PSweights_13TeV-powheg-pythia8_48.out
Error = TT_Mtt-700to1000_TuneCP5_PSweights_13TeV-powheg-pythia8_48.err
Log = TT_Mtt-700to1000_TuneCP5_PSweights_13TeV-powheg-pythia8_48.log
Notification = Never
Arguments = "TT_Mtt-700to1000_TuneCP5_PSweights_13TeV-powheg-pythia8 TT_Mtt-700to1000_TuneCP5_PSweights_13TeV-powheg-pythia8 /store/user/lpcljm/FWLJMET102X_1lep2017_052219//TT_Mtt-700to1000_TuneCP5_PSweights_13TeV-powheg-pythia8/singleLep2017/190528_215307/0001 /mnt/hadoop/store/user/jblee/CHiggs2017/nominal//TT_Mtt-700to1000_TuneCP5_PSweights_13TeV-powheg-pythia8 '1390 1391 1392 1393 1394 1395 1396 1397 1398 1399 1400 1401 1402 1403 1404 1405 1406 1407 1408 1409 1410 1411 1412 1413 1414 1415 1416 1417 1418 1419' 48"

Queue 1