use_x509userproxy = true
universe = vanilla
Executable = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/makeStep1brux.sh
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
Transfer_Input_Files = /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/makeStep1.C, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1.cc, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1.h, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1_cc.d, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/step1_cc.so, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/BTagCalibForLJMet.cpp, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/BTagCalibForLJMet.h, /user_data/jlee/chargedHiggs/2017Data/CMSSW_10_2_10/src/step1/DeepCSV_94XSF_V4_B_F.csv
Output = TT_Mtt-700to1000_TuneCP5_PSweights_13TeV-powheg-pythia8_8.out
Error = TT_Mtt-700to1000_TuneCP5_PSweights_13TeV-powheg-pythia8_8.err
Log = TT_Mtt-700to1000_TuneCP5_PSweights_13TeV-powheg-pythia8_8.log
Notification = Never
Arguments = "TT_Mtt-700to1000_TuneCP5_PSweights_13TeV-powheg-pythia8 TT_Mtt-700to1000_TuneCP5_PSweights_13TeV-powheg-pythia8 /store/user/lpcljm/FWLJMET102X_1lep2017_052219//TT_Mtt-700to1000_TuneCP5_PSweights_13TeV-powheg-pythia8/singleLep2017/190528_215307/0000 /mnt/hadoop/store/user/jblee/CHiggs2017/nominal//TT_Mtt-700to1000_TuneCP5_PSweights_13TeV-powheg-pythia8 '289 29 290 291 292 293 294 295 296 297 298 299 3 30 300 301 302 303 304 305 306 307 308 309 31 310 311 312 313 314' 8"

Queue 1